/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Java.Project;

public class App {
   
    public static void main(String[] args) {
        Car c1 = new Car("Petrol", "Bentley", 335);
        System.out.println(c1.getEngineType() + " " + c1.brand );
    }
}
